/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface FreeRaffleEntry {
  'entryCount' : bigint,
  'walletAddress' : string,
  'lastClickAt' : Timestamp,
  'registeredAt' : Timestamp,
}
export interface PurchaseRecord {
  'tiers' : Array<bigint>,
  'principal' : Principal,
  'walletAddress' : [] | [string],
}
export type PurchaseResult = { 'ok' : null } |
  { 'err' : { 'duplicate' : null } | { 'invalidTier' : null } };
export type RaffleResult = { 'ok' : null } |
  { 'cooldownActive' : null } |
  { 'alreadyRegistered' : null } |
  { 'notRegistered' : null };
export type RaffleStatus = {
    'ok' : { 'entryCount' : bigint, 'lastClickAt' : bigint }
  } |
  { 'notRegistered' : null };
export type RegisterResult = { 'ok' : null } |
  { 'err' : { 'duplicate' : null } | { 'invalidTier' : null } };
export interface Registration {
  'tier' : Tier,
  'walletAddress' : string,
  'timestamp' : Timestamp,
}
export type Tier = bigint;
export interface TierCounts {
  'tier1' : bigint,
  'tier2' : bigint,
  'tier3' : bigint,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'claimDailyEntry' : ActorMethod<[string], RaffleResult>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFreeRaffleStatus' : ActorMethod<[string], RaffleStatus>,
  'getMyPurchases' : ActorMethod<[], Array<bigint>>,
  'getTierCounts' : ActorMethod<[string], TierCounts>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllPurchases' : ActorMethod<[string], Array<PurchaseRecord>>,
  'listRaffleEntries' : ActorMethod<[string], Array<FreeRaffleEntry>>,
  'listRegistrations' : ActorMethod<[string], Array<Registration>>,
  'recordPurchaseVerification' : ActorMethod<[bigint, string], PurchaseResult>,
  'registerRaffle' : ActorMethod<[string], RaffleResult>,
  'registerWallet' : ActorMethod<[string, bigint], RegisterResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];