/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const RaffleResult = IDL.Variant({
  'ok' : IDL.Null,
  'cooldownActive' : IDL.Null,
  'alreadyRegistered' : IDL.Null,
  'notRegistered' : IDL.Null,
});
export const RaffleStatus = IDL.Variant({
  'ok' : IDL.Record({ 'entryCount' : IDL.Nat, 'lastClickAt' : IDL.Int }),
  'notRegistered' : IDL.Null,
});
export const TierCounts = IDL.Record({
  'tier1' : IDL.Nat,
  'tier2' : IDL.Nat,
  'tier3' : IDL.Nat,
});
export const PurchaseRecord = IDL.Record({
  'tiers' : IDL.Vec(IDL.Nat),
  'principal' : IDL.Principal,
  'walletAddress' : IDL.Opt(IDL.Text),
});
export const Timestamp = IDL.Int;
export const FreeRaffleEntry = IDL.Record({
  'entryCount' : IDL.Nat,
  'walletAddress' : IDL.Text,
  'lastClickAt' : Timestamp,
  'registeredAt' : Timestamp,
});
export const Tier = IDL.Nat;
export const Registration = IDL.Record({
  'tier' : Tier,
  'walletAddress' : IDL.Text,
  'timestamp' : Timestamp,
});
export const PurchaseResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Variant({ 'duplicate' : IDL.Null, 'invalidTier' : IDL.Null }),
});
export const RegisterResult = IDL.Variant({
  'ok' : IDL.Null,
  'err' : IDL.Variant({ 'duplicate' : IDL.Null, 'invalidTier' : IDL.Null }),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'claimDailyEntry' : IDL.Func([IDL.Text], [RaffleResult], []),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFreeRaffleStatus' : IDL.Func([IDL.Text], [RaffleStatus], ['query']),
  'getMyPurchases' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getTierCounts' : IDL.Func([IDL.Text], [TierCounts], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllPurchases' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PurchaseRecord)],
      ['query'],
    ),
  'listRaffleEntries' : IDL.Func([IDL.Text], [IDL.Vec(FreeRaffleEntry)], []),
  'listRegistrations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Registration)],
      ['query'],
    ),
  'recordPurchaseVerification' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [PurchaseResult],
      [],
    ),
  'registerRaffle' : IDL.Func([IDL.Text], [RaffleResult], []),
  'registerWallet' : IDL.Func([IDL.Text, IDL.Nat], [RegisterResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const RaffleResult = IDL.Variant({
    'ok' : IDL.Null,
    'cooldownActive' : IDL.Null,
    'alreadyRegistered' : IDL.Null,
    'notRegistered' : IDL.Null,
  });
  const RaffleStatus = IDL.Variant({
    'ok' : IDL.Record({ 'entryCount' : IDL.Nat, 'lastClickAt' : IDL.Int }),
    'notRegistered' : IDL.Null,
  });
  const TierCounts = IDL.Record({
    'tier1' : IDL.Nat,
    'tier2' : IDL.Nat,
    'tier3' : IDL.Nat,
  });
  const PurchaseRecord = IDL.Record({
    'tiers' : IDL.Vec(IDL.Nat),
    'principal' : IDL.Principal,
    'walletAddress' : IDL.Opt(IDL.Text),
  });
  const Timestamp = IDL.Int;
  const FreeRaffleEntry = IDL.Record({
    'entryCount' : IDL.Nat,
    'walletAddress' : IDL.Text,
    'lastClickAt' : Timestamp,
    'registeredAt' : Timestamp,
  });
  const Tier = IDL.Nat;
  const Registration = IDL.Record({
    'tier' : Tier,
    'walletAddress' : IDL.Text,
    'timestamp' : Timestamp,
  });
  const PurchaseResult = IDL.Variant({
    'ok' : IDL.Null,
    'err' : IDL.Variant({ 'duplicate' : IDL.Null, 'invalidTier' : IDL.Null }),
  });
  const RegisterResult = IDL.Variant({
    'ok' : IDL.Null,
    'err' : IDL.Variant({ 'duplicate' : IDL.Null, 'invalidTier' : IDL.Null }),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'claimDailyEntry' : IDL.Func([IDL.Text], [RaffleResult], []),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFreeRaffleStatus' : IDL.Func([IDL.Text], [RaffleStatus], ['query']),
    'getMyPurchases' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getTierCounts' : IDL.Func([IDL.Text], [TierCounts], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllPurchases' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PurchaseRecord)],
        ['query'],
      ),
    'listRaffleEntries' : IDL.Func([IDL.Text], [IDL.Vec(FreeRaffleEntry)], []),
    'listRegistrations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Registration)],
        ['query'],
      ),
    'recordPurchaseVerification' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [PurchaseResult],
        [],
      ),
    'registerRaffle' : IDL.Func([IDL.Text], [RaffleResult], []),
    'registerWallet' : IDL.Func([IDL.Text, IDL.Nat], [RegisterResult], []),
  });
};

export const init = ({ IDL }) => { return []; };