/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type RegisterResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Variant_duplicate_invalidTier;
};
export type Timestamp = bigint;
export interface TierCounts {
    tier1: bigint;
    tier2: bigint;
    tier3: bigint;
}
export type PurchaseResult = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Variant_duplicate_invalidTier;
};
export interface PurchaseRecord {
    tiers: Array<bigint>;
    principal: Principal;
    walletAddress?: string;
}
export interface Registration {
    tier: Tier;
    walletAddress: string;
    timestamp: Timestamp;
}
export type RaffleStatus = {
    __kind__: "ok";
    ok: {
        entryCount: bigint;
        lastClickAt: bigint;
    };
} | {
    __kind__: "notRegistered";
    notRegistered: null;
};
export type Tier = bigint;
export interface FreeRaffleEntry {
    entryCount: bigint;
    walletAddress: string;
    lastClickAt: Timestamp;
    registeredAt: Timestamp;
}
export enum RaffleResult {
    ok = "ok",
    cooldownActive = "cooldownActive",
    alreadyRegistered = "alreadyRegistered",
    notRegistered = "notRegistered"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_duplicate_invalidTier {
    duplicate = "duplicate",
    invalidTier = "invalidTier"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    claimDailyEntry(walletAddress: string): Promise<RaffleResult>;
    getCallerUserRole(): Promise<UserRole>;
    getFreeRaffleStatus(walletAddress: string): Promise<RaffleStatus>;
    getMyPurchases(): Promise<Array<bigint>>;
    getTierCounts(password: string): Promise<TierCounts>;
    isCallerAdmin(): Promise<boolean>;
    listAllPurchases(password: string): Promise<Array<PurchaseRecord>>;
    listRaffleEntries(password: string): Promise<Array<FreeRaffleEntry>>;
    listRegistrations(password: string): Promise<Array<Registration>>;
    recordPurchaseVerification(tier: bigint, stripeSessionId: string): Promise<PurchaseResult>;
    registerRaffle(walletAddress: string): Promise<RaffleResult>;
    registerWallet(walletAddress: string, tier: bigint): Promise<RegisterResult>;
}
import type { PurchaseRecord as _PurchaseRecord, PurchaseResult as _PurchaseResult, RaffleResult as _RaffleResult, RaffleStatus as _RaffleStatus, RegisterResult as _RegisterResult, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async claimDailyEntry(arg0: string): Promise<RaffleResult> {
        if (this.processError) {
            try {
                const result = await this.actor.claimDailyEntry(arg0);
                return from_candid_RaffleResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimDailyEntry(arg0);
            return from_candid_RaffleResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFreeRaffleStatus(arg0: string): Promise<RaffleStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getFreeRaffleStatus(arg0);
                return from_candid_RaffleStatus_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFreeRaffleStatus(arg0);
            return from_candid_RaffleStatus_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPurchases(): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPurchases();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPurchases();
            return result;
        }
    }
    async getTierCounts(arg0: string): Promise<TierCounts> {
        if (this.processError) {
            try {
                const result = await this.actor.getTierCounts(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTierCounts(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllPurchases(arg0: string): Promise<Array<PurchaseRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllPurchases(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllPurchases(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async listRaffleEntries(arg0: string): Promise<Array<FreeRaffleEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRaffleEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRaffleEntries(arg0);
            return result;
        }
    }
    async listRegistrations(arg0: string): Promise<Array<Registration>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRegistrations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRegistrations(arg0);
            return result;
        }
    }
    async recordPurchaseVerification(arg0: bigint, arg1: string): Promise<PurchaseResult> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPurchaseVerification(arg0, arg1);
                return from_candid_PurchaseResult_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPurchaseVerification(arg0, arg1);
            return from_candid_PurchaseResult_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerRaffle(arg0: string): Promise<RaffleResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerRaffle(arg0);
                return from_candid_RaffleResult_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerRaffle(arg0);
            return from_candid_RaffleResult_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerWallet(arg0: string, arg1: bigint): Promise<RegisterResult> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWallet(arg0, arg1);
                return from_candid_RegisterResult_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWallet(arg0, arg1);
            return from_candid_RegisterResult_n16(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_PurchaseRecord_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseRecord): PurchaseRecord {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_PurchaseResult_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PurchaseResult): PurchaseResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_RaffleResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RaffleResult): RaffleResult {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_RaffleStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RaffleStatus): RaffleStatus {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_RegisterResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RegisterResult): RegisterResult {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    tiers: Array<bigint>;
    principal: Principal;
    walletAddress: [] | [string];
}): {
    tiers: Array<bigint>;
    principal: Principal;
    walletAddress?: string;
} {
    return {
        tiers: value.tiers,
        principal: value.principal,
        walletAddress: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.walletAddress))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: {
        duplicate: null;
    } | {
        invalidTier: null;
    };
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Variant_duplicate_invalidTier;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_variant_n15(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duplicate: null;
} | {
    invalidTier: null;
}): Variant_duplicate_invalidTier {
    return "duplicate" in value ? Variant_duplicate_invalidTier.duplicate : "invalidTier" in value ? Variant_duplicate_invalidTier.invalidTier : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    cooldownActive: null;
} | {
    alreadyRegistered: null;
} | {
    notRegistered: null;
}): RaffleResult {
    return "ok" in value ? RaffleResult.ok : "cooldownActive" in value ? RaffleResult.cooldownActive : "alreadyRegistered" in value ? RaffleResult.alreadyRegistered : "notRegistered" in value ? RaffleResult.notRegistered : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: {
        entryCount: bigint;
        lastClickAt: bigint;
    };
} | {
    notRegistered: null;
}): {
    __kind__: "ok";
    ok: {
        entryCount: bigint;
        lastClickAt: bigint;
    };
} | {
    __kind__: "notRegistered";
    notRegistered: null;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "notRegistered" in value ? {
        __kind__: "notRegistered",
        notRegistered: value.notRegistered
    } : value;
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PurchaseRecord>): Array<PurchaseRecord> {
    return value.map((x)=>from_candid_PurchaseRecord_n10(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
